general.import = ["./theme.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10 

decorations = "Buttonless"
opacity = 1
blur = true

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 16


